### ISSUE TITLE
How did you train your network on TCGA-NSCLC dataset for three manifications?

### ISSUE THREAD

**Issue by Lewislou** [BearCleverProud/HAG-MIL#2]
I have noticed some WSI in NSCLC dataset do not have level 2, so how did you extract patches for these images for your framework?
For example: TCGA-05-4384-01Z-00-DX1.CA68BF29-BBE3-4C8E-B48B-554431A9EE13.svs, TCGA-63-A5MH-01Z-00-DX1.596077FF-9CE1-4EA7-9BB6-222C69872CA4.svs and many others.

**Comment by Lewislou** [comment]
![image](https://github.com/BearCleverProud/HAG-MIL/assets/23080469/11b37866-735b-493d-9330-4cfe20592302)

**Comment by BearCleverProud** [comment]
> I have noticed some WSI in NSCLC dataset do not have level 2, so how did you extract patches for these images for your framework? For example: TCGA-05-4384-01Z-00-DX1.CA68BF29-BBE3-4C8E-B48B-554431A9EE13.svs, TCGA-63-A5MH-01Z-00-DX1.596077FF-9CE1-4EA7-9BB6-222C69872CA4.svs and many others.

We actually operates on level 1 and level 0 only for TCGA datasets, NO level 2. Sorry for the confusion.

**Comment by homadnmr** [comment]
Thanks for your perfect work. I have a question: CLAM "create_patches_fp.py" provides csv file after segmentation and patching and this csv file will be used in feature extraction. then we use your script "create_quadtree_wsis.py" to provide the corresponding patches in level1 and level 0 but it does not provide csv file. SO the question is, as for level1 and level0 patches we do not have csv file how can we use "extract_features_fp.py" to extract the features of corresponding patches of level one and zero???

**Comment by bravePinocchio** [comment]
May I ask how this problem can be solved?

**Comment by bravePinocchio** [comment]
May I ask if tcga does not have level2, so when processing patch level = 1, does it represent 20x resolution, i.e. is tcga processing at 20x and 40x?

**Comment by BearCleverProud** [comment]
> May I ask if tcga does not have level2, so when processing patch level = 1, does it represent 20x resolution, i.e. is tcga processing at 20x and 40x?

Yes, that is correct.
