### ISSUE TITLE
CSV files of level 1 & level 0???

### ISSUE THREAD

**Issue by homadnmr** [BearCleverProud/HAG-MIL#3]
Thanks for your perfect work. I have a question: CLAM "create_patches_fp.py" provides csv file after segmentation and patching  of level2 and this csv file will be used in feature extraction. then we use your script "create_quadtree_wsis.py" to provide the corresponding patches in level1 and level 0 but it does not provide csv . SO the question is, as for level1 and level0 patches we do not have csv file  ( as create_quadtree_wsis.py" does not generate such csv file), how can we use "extract_features_fp.py" without that CSV file to extract the features of corresponding patches of level one and zero???

**Comment by BearCleverProud** [comment]
Hello! 

You can just use the generated level2 csv file, as they are essentially the same name with minor changes.

Also, if you would like to, you may create a csv file with the same structure using very simple python codes based the generated .h5 folder.
